/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options passed to `new Recorder({...})` from JS. */
export interface RecorderOptions {
  /** Absolute path where the MP4 will be written. */
  output: string
  /** Optional monitor id. If omitted, records the primary display. */
  monitorId?: number
  /** Reserved for future MP4 audio muxing. Accepted today but not recorded. */
  microphone?: boolean
  /** Reserved for future system-audio muxing. Accepted today but not recorded. */
  systemAudio?: boolean
  /**
   * Substring patterns matched against the focused app name and window title
   * (case-insensitive). While a matching window is in focus, the recorder
   * skips writing frames — the MP4 contains a hard cut over the filtered
   * period. Mirrors the engine's `--ignored-windows` CLI flag.
   */
  ignoredWindows?: Array<string>
  /**
   * Substring whitelist. If non-empty, frames are written ONLY while the
   * focused app name or window title matches at least one pattern.
   * Mirrors the engine's `--included-windows` CLI flag.
   */
  includedWindows?: Array<string>
  /**
   * URL patterns to skip (case-insensitive, domain-aware matching).
   * When the focused window is a browser navigated to a matching URL,
   * the recorder skips writing frames. Mirrors `--ignored-urls`.
   */
  ignoredUrls?: Array<string>
}
/** Permission status returned by `requestPermissions`. */
export interface PermissionStatus {
  /** Screen recording permission granted. */
  screen: boolean
  /** Microphone permission granted. */
  microphone: boolean
}
/**
 * Lightweight snapshot of the user's focused window. Returned by
 * `Recorder.focusedApp()`. All fields are best-effort — on some
 * platforms/apps only `appName` is reliably populated.
 */
export interface FocusedApp {
  appName: string
  windowTitle: string
  browserUrl?: string
  nodeCount: number
  walkMs: number
}
/**
 * Current state of the window/URL filter. Returned by
 * `Recorder.filterStatus()`. When `paused` is true, the capture loop is
 * dropping frames — `reason` is a short tag identifying which rule fired
 * (`"ignored_window"`, `"included_window_mismatch"`, `"ignored_url"`,
 * `"incognito"`, `"excluded_app"`). Both fields are `null`/`false` when
 * no filter is configured or when a11y permission has not been granted.
 */
export interface FilterStatus {
  paused: boolean
  reason?: string
}
/**
 * Patch passed to `Recorder.setFilters({...})` for live filter updates.
 * Any field omitted (or sent as `null`) clears that list. All three fields
 * follow the same matching semantics as the matching `RecorderOptions`
 * fields.
 */
export interface FilterPatch {
  ignoredWindows?: Array<string>
  includedWindows?: Array<string>
  ignoredUrls?: Array<string>
}
/**
 * Prompt the OS for screen recording + microphone permissions if not already
 * granted. On macOS this triggers the TCC dialog the first time; on
 * subsequent calls it just reports current state.
 *
 * Returns `{ screen, microphone }` booleans.
 */
export declare function requestPermissions(): Promise<PermissionStatus>
/**
 * Record a user's screen to an MP4 file.
 *
 * ```ts
 * import { Recorder } from '@screenpipe/sdk';
 *
 * const r = new Recorder({ output: '/tmp/session.mp4' });
 * await r.start();
 * // ... user does stuff ...
 * await r.stop();
 * ```
 */
export declare class Recorder {
  /** Construct a recorder. Does NOT start capture — call `.start()`. */
  constructor(options: RecorderOptions)
  /**
   * Begin writing frames to the output file. Resolves once the
   * capture stream is live and the MP4 header has been written.
   */
  start(): Promise<void>
  /**
   * Stop capture. Flushes the MP4 trailer and closes the file. Idempotent
   * (safe to call twice).
   */
  stop(): Promise<void>
  /**
   * Capture a single frame of the recorder's monitor as a JPEG buffer.
   * Works whether or not `start()` has been called — useful for live
   * thumbnail previews in UIs embedding the SDK.
   */
  snapshot(): Promise<Buffer>
  /**
   * Number of frames written to the MP4 since `start()`. Useful for
   * live UI stats. Returns 0 if not recording.
   */
  framesWritten(): Promise<number>
  /**
   * Current microphone input level in [0, 1] (smoothed linear RMS).
   * The first call starts a persistent capture on the default input
   * device and triggers the macOS Microphone TCC prompt if not yet
   * granted. Independent of `start()` — works as a pre-flight meter.
   */
  audioLevel(): Promise<number>
  /**
   * Current state of the window/URL filter — see `FilterStatus`. Polled
   * by host integrations to drive UI ("⏸ paused — banking site") or to
   * count skipped frames. Returns `{ paused: false, reason: undefined }`
   * when no filter is configured.
   */
  filterStatus(): Promise<FilterStatus>
  /**
   * Replace the active filter lists at runtime. Each field in `patch`
   * either provides a new list or — when omitted — clears that list. The
   * next focus-watcher tick (≤ 1 s later) re-evaluates the current focused
   * window against the updated rules.
   */
  setFilters(patch: FilterPatch): Promise<void>
  /**
   * Snapshot of the currently focused window via accessibility APIs.
   * Returns `null` when no focused window is detected or the window
   * is on the skip-list (incognito, excluded app).
   *
   * macOS: requires Accessibility permission (System Settings →
   * Privacy & Security → Accessibility). The first call may silently
   * return `null` until the user grants it — the SDK does not raise
   * the dialog itself on macOS, callers should prompt out of band.
   */
  focusedApp(): Promise<FocusedApp | null>
}
